Add autoscroll and animation to intro carousel
status-im/status-legacy pull request #10894
Opened 2020-06-30 11:57 UTC by Ferossgp

Fixes #10724

2020-06-30 12:07 UTC, flexsurfer approved these changes

2020-06-30 12:11 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 81753340 | [#1](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-10894/1/) | 2020-06-30 12:11:55 | ~14 min | `ios` | [:package:`ipa`](https://i.diawi.com/DywMjE) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FDywMjE)|

2020-06-30 12:17 UTC, errorists requested changes
Animation and autoscroll stops once I interact with the carousel, that's not okay and should be fixed before I can approve it

2020-06-30 17:28 UTC, errorists approved these changes

2020-07-01 02:01 UTC, oskarth commented
Small request - could you please rebase to latest master so this commit https://github.com/status-im/status-react/commit/b5fda1234e5447cbc626059dfc78fcfbabc9e926 gets included? This means we aren't running E2E tests on eth.prod cluster anymore, and since this happens on every push, the impact is quite big. This ensures we have more accurate metrics going forward from Jul 1 onward, which would be awesome. See https://discuss.status.im/t/user-growth-and-retention/1782 for more

2020-07-01 06:32 UTC, merged