Add goerli testnet
status-im/status-legacy pull request #7734
Opened 2019-03-14 09:25 UTC by dshulyak

2019-03-14 09:33 UTC, mandrigin commented
@dshulyak thanks! we probably need a status-go update too, right?

2019-03-14 09:42 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 0766bbb5 | [#1](https://ci.status.im/job/status-react/job/prs/job/macos/job/PR-7734/1/) | 2019-03-14 09:42:15 | ~16 min | `macos` | [:package: dmg](https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190314-092534-0766bb-pr.dmg) |

2019-03-15 07:51 UTC, dshulyak commented
@mandrigin yes, i had some problems with a status-go build. i will make a status-go release a bit later

2019-04-12 09:00 UTC, mandrigin requested changes

2019-04-12 09:00 UTC, mandrigin commented on STATUS_GO_VERSION
> +190315-072737-3049ad
I think this change is unnecessary, otherwise looks good.

2019-04-30 07:26 UTC, mandrigin commented
@dshulyak can you maybe update the status-go version to the current one, then we can merge it?

2019-04-30 16:12 UTC, PombeirP commented
By the way, just to make sure we're on the same page, it's no longer necessary to build status-go on Jenkins before building with updated version in status-react, since Nix will build status-go package as part of its build.

2019-05-24 08:59 UTC, flexsurfer commented
@mandrigin @dshulyak is this still relevant?

2019-05-24 09:17 UTC, mandrigin commented
we probably should rebase, test and merge it

2019-05-27 12:42 UTC, jakubgs commented
I'd like to revive this. Ropsten has been getting worse and worse in terms of syncing:
![rops_les_sync](https://user-images.githubusercontent.com/2212681/58420387-243f0580-805b-11e9-9e9f-d31658f7d976.png)
https://grafana.status.im/d/VyUgFRWZz/geth-syncing?orgId=1&var-fleet=rops.les&from=now-2d&to=now
![faucet_ropsten_sync](https://user-images.githubusercontent.com/2212681/58420397-299c5000-805b-11e9-960a-6bdb55b1670d.png)
https://grafana.status.im/d/VyUgFRWZz/geth-syncing?orgId=1&from=now-13d&to=now&var-fleet=faucet.ropsten
I'd love to switch to the [Görli](https://goerli.net/)(`goerli`) network so we could replace `les.rops` and `faucet.ropsten` fleets with `les.goerli` and `faucet.goerli`. I intend to deploy these two today and see how well it sync.

2019-05-27 13:42 UTC, jakubgs commented
Created a Discuss post about this:
https://discuss.status.im/t/replacing-ropsten-with-gorli-network-for-faucet-and-les-needs/1235

2019-05-28 15:33 UTC, mandrigin approved these changes

2019-05-28 15:33 UTC, mandrigin commented
@flexsurfer ready to be reviewed, tested an merged ;-)

2019-05-28 15:36 UTC, yenda approved these changes

2019-05-28 15:38 UTC, flexsurfer approved these changes

2019-05-29 08:30 UTC, asemiankevich commented
@dshulyak @mandrigin do we have a faucet here? Wondering if i can test transactions

2019-05-29 08:31 UTC, mandrigin commented
@asemiankevich not yet, but @jakubgs wanted to try moving our fauced from ropsten to goerli.

@jakubgs do we have some test faucet for it?

2019-05-29 09:25 UTC, asemiankevich commented
What i have noticed so far:  
- using status-im.github.io/dapp I cant sign Typed message ( transaction -> sign Typed message). wrong password appears. @flexsurfer maybe you could clarify here?
- none of transactions are mined, 0 confirmations  :( Seems to be expected as not many users are using this network?

2019-05-29 09:38 UTC, mandrigin commented
@asemiankevich hmm, that is interesting... I wonder how can we test goerli separately from Status?

2019-05-29 09:39 UTC, asemiankevich commented
> @asemiankevich hmm, that is interesting... I wonder how can we test goerli separately from Status?

metamask should work, i can try there

2019-05-29 11:14 UTC, asemiankevich commented
@mandrigin this Sign typed message does not work on Goerli in metamask at all, the call is not being performed, i dont see any sign message screen. Also i found that transaction history is not populated 
![image](https://user-images.githubusercontent.com/28752642/58552694-b55cda80-821b-11e9-9b3e-ec237a5821d4.png)

@mandrigin we could probably merge the PR, since i can switch to this network and send some messages and transactions, issues with history, mining and sign typed message i believe are network-related and we can work on this later, right? cc @annadanchenko

2019-05-29 12:59 UTC, merged

2019-05-29 17:17 UTC, jakubgs commented
>@jakubgs do we have some test faucet for it?

@mandrigin @asemiankevich We do now: https://faucet-goerli.status.im/faucet-info