Feature/rework ttt
status-im/status-legacy pull request #8304
Opened 2019-05-29 09:49 UTC by yenda

[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

If you submit PR for issue with bounty then write here Fixes #NN where NN is issue number

*otherwise*

fixes #...

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
...

Documentation change PR (review please): https://github.com/status-im/status.im/pull/xxx

### Review notes

### Testing notes

#### Platforms

- Android
- iOS
- macOS
- Linux
- Windows

#### Areas that maybe impacted

##### Functional

- 1-1 chats
- public chats
- group chats
- wallet / transactions
- dapps / app browsing
- account recovery
- new account
- user profile updates
- networks
- mailservers
- fleet
- bootnodes

##### Non-functional

- battery performance
- CPU performance / speed of the app
- network consumption

### Steps to test

- Open Status
- ...
- Step 3, etc.

status: ready

2019-05-29 09:54 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 9c7fd208 | [#1](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-8304/1/) | 2019-05-29 09:54:13 | ~4 min | `ios` | [:page_facing_up: log](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-8304/1/consoleText) |

2019-05-31 10:48 UTC, vitvly approved these changes

2019-05-31 11:08 UTC, flexsurfer approved these changes

2019-05-31 11:08 UTC, flexsurfer commented on src/status_im/data_store/contacts.cljs
> +      (update :tribute-to-talk edn/read-string)
we use transit for account settings

2019-05-31 12:25 UTC, cammellos requested changes
Please add some tests
@siphiuel @flexsurfer please do not approve large PRs with at least a bare minimum test coverage

2019-05-31 12:40 UTC, yenda commented
@annadanchenko @churik please proceed with testing writing tests won't impact anything

2019-05-31 13:15 UTC, asemiankevich commented
we are working on this @yenda :)

2019-05-31 16:24 UTC, yenda commented
@cammellos tests added please review again

2019-05-31 16:31 UTC, churik commented
@yenda 
#### 1) If TTT is set on both account in chat, only one of them should pay
Is it expected? I'm not sure
**Steps:**
- create 2 accounts (A and B)
- change network to Ropsten
- as user A: set TTT
- as user B: set TTT
- as user A: open profile of user B
- as user A: pay TTT and send message to user A
Currently after this User A and User B can chat regardless that User B didn't pay TTT for user A.

#### 2) User is not added in contacts, but TTT says that user is added to contacts after paying TTT
![download](https://user-images.githubusercontent.com/4557972/58718807-92bef300-83ce-11e9-9ec5-e3ba24dec574.png)

#### 3) Buttons are overlapped on some phones
<img width="440" alt="Screenshot at May 31 18-08-11" src="https://user-images.githubusercontent.com/4557972/58719032-124cc200-83cf-11e9-84e5-f33d5b418d12.png">
Device: huawei p10 lite android8 5.2»

#### 4) No warning that TTT is set when user sends a message from a different network

**Steps:**
- create 2 accounts (A and B)
- as user A: change network to Ropsten
- as user A:  set TTT
- as user B: send message to user A (on mainnet)
**Expected result:**  can see that need to change network to contact user A, message sending is not possible
**Actual result:** message is sent, but in fact, it is not received and it will never be received.

#### 5) Warning with TTT enabled is shown on wallet screen
I don't think that this is expected
<img width="440" alt="Screenshot at May 31 18-08-11" src="https://user-images.githubusercontent.com/4557972/58719853-fea25b00-83d0-11e9-8dc9-597c759b7e81.png">

#### 6) On message TTT is paid no timestamp (design)
@errorists can you elaborate why on message "Tribute is paid" no timestamp is shown?
![IMG_52B290F60830-1](https://user-images.githubusercontent.com/4557972/58720020-5c36a780-83d1-11e9-8fa2-c2cef077afb2.jpeg)

#### 7) @rachelhamlin it will be breaking change for previous builds, right?
So now: if user from the previous build sends a message to user with TTT enabled, it just will be never received and both sides will not be notified about it.

2019-05-31 16:37 UTC, yenda commented
@churik 

1. yes that is normal, only one side needs to pay for the conversation to start
2. we could improve the copy here but user is not added in contacts so showing the add to contact here is correct
3. will have a look
4. this cannot be done, that's the way it is
5. wrong picture?
6. it's not a message it's state
7. yes they will never receive the message

I'm going to make a build with ttt disabled please test it to see if we can merge this, we will handle the fixes separately

2019-05-31 16:46 UTC, churik commented
@yenda changed the image for 5, mistake - sorry

2019-05-31 16:56 UTC, yenda commented
@churik ok I made one more PR with ttt enabled to test fixes for 2 3 and 5

2019-05-31 16:57 UTC, yenda commented
once it is built I will make a final build without ttt enabled

2019-05-31 17:23 UTC, yenda commented
@churik 
Build 32: ttt enabled on ropsten
Build 33: ttt disabled

2019-05-31 17:23 UTC, cammellos approved these changes

2019-06-03 10:34 UTC, churik commented
@yenda thanks for fixes: verified all. New issues:

### on build 32:
#### 8. Can't get messages after paying TTT
**Steps:**
- create 2 accounts (A and B)
- change network to Ropsten
- as user A: set TTT
- as user B: pay TTT and send message to user A
**Expected result:** user A will receive a message
**Actual result:** user A doesn't receive messages.
Ao basically chat flow is not working on build 32.

#### 9. "Tribute paid" message is always visible when open chat regardless of the message order
**Steps:**
- create 2 accounts (A and B)
- change network to Ropsten
- as user A: set TTT
- as user B: pay TTT and send message to user A
- as user B: send 10+ messages to user A
- go back and open chat with user A again

**Expected result:** can see last 10 messages, "Tribute paid" message is not shown until I will scroll manually to the start of the history
**Actual result:**  "Tribute paid" message is shown
**Video:** https://drive.google.com/open?id=1KxhDHWkruqATKLr3Q9rPR_9qSTeBRlSq

#### 10. "Confirmed" is shown on "Failed" transaction in chat (likely in nightly as well)
I don't have steps to reproduce, it just transaction for paying TTT is failed with "Out of gas" error - but in chat, I see that transaction is confirmed.
Transaction: https://ropsten.etherscan.io/tx/0x6429f6b29c306d5d62e977b64220678f746edaed20c82447b8f38e5ce48286d7
How it looks in chat and in transaction history accordingly:
![photo_2019-06-03 12 24 02 jpeg 2019-06-03 12-24-39](https://user-images.githubusercontent.com/4557972/58795402-d9913080-85fa-11e9-9588-4fae49d2cf64.png)
[Status-debug-logs.zip](https://github.com/status-im/status-react/files/3247071/Status-debug-logs.zip)

### on build 32 and 33:
#### 11. No preview on home for last messages in public and group chat
**Steps:**
- create account
- join any public chat with messages
- tap back
**Expected result:** can see the preview of the last message
**Actual result:** no preview
![IMG_BD45AF7E37BC-1 jpeg 2019-06-03 12-32-27](https://user-images.githubusercontent.com/4557972/58795726-aef3a780-85fb-11e9-9b67-302329a33394.png)

2019-06-03 11:04 UTC, yenda commented
@churik Let's focus on build without ttt from now on. Fixed the last message it was just a wrong condition for group-chats. Can you create issues for the ttt enabled buid? I will make a seperate PR enabling ttt and fixing these issues

2019-06-03 12:04 UTC, churik commented
@yenda 
no preview for "No messages" in last build (34)
![IMG_0F3DC0EF6D1D-1](https://user-images.githubusercontent.com/4557972/58800569-845c1b80-8608-11e9-91a6-4f661b8718a5.jpeg)

2019-06-03 12:09 UTC, yenda commented
@churik damn, fixed

2019-06-03 12:12 UTC, churik commented
@yenda one more:
error when when enable "Preview privacy mode" in Profile.
![IMG_9CDEA0EF12B7-1](https://user-images.githubusercontent.com/4557972/58801008-a73aff80-8609-11e9-8478-26f03b0ab11d.jpeg)

[status_logs1.zip](https://github.com/status-im/status-react/files/3247483/status_logs1.zip)

2019-06-03 12:14 UTC, yenda commented
@churik no related to this PR

2019-06-03 12:23 UTC, yenda commented
@churik fixed here https://github.com/status-im/status-react/pull/8345/files

2019-06-03 13:24 UTC, churik commented
Checked Mac OS build (chatting) - no difference from my POV with current nightly.
Full regression from build 33: https://ethstatus.testrail.net/index.php?/runs/view/3505 (no regression found by e2e)
Checked IOS and Android on build 35:
- issue with preview is fixed
- no TTT in Profile
- chatting 
- sending transactions.

All issues when TTT is enabled will be added and fixed separately.

2019-06-03 13:31 UTC, merged