Use react-native-fast-image for remote images #7633
status-im/status-legacy pull request #8399
Opened 2019-06-10 12:57 UTC by shamardy

Fixes #7633

2019-06-10 12:58 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | d404c04d | [#1](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-8399/1/) | 2019-06-10 12:58:49 | ~51 sec | `ios` | [:page_facing_up: log](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-8399/1/consoleText) |

2019-06-11 07:25 UTC, flexsurfer commented
hey @shamardy is it WIP?

2019-06-11 07:35 UTC, shamardy commented
> hey @shamardy is it WIP?

No. Also I dont have Overall/Read permission in Jenkins to check the logs and errors.

2019-06-11 08:56 UTC, flexsurfer commented
but i couldn't find any usage of this new component in the code, we should replace react native image on this new component

2019-06-12 07:37 UTC, flexsurfer requested changes
thanks for the contribution @shamardy left some comments

2019-06-12 07:37 UTC, flexsurfer commented on react-native/src/desktop/status_im/react_native/js_dependencies.cljs
> +(def fast-image             (fn [] #js {}))
i'm not sure about desktop, @vkjr ?

2019-06-12 07:37 UTC, flexsurfer commented on src/status_im/extensions/capacities/components.cljs
> +  [rn-dependencies/fast-image (merge {:style (merge {:width 100 :height 100} style)} {:source (if source source {:uri uri})})])
we need to replace usage of class inside react/image itself, here https://github.com/status-im/status-react/blob/c2b55233225f6e4d59c9ca5174b5261cc1137fec/components/src/status_im/ui/components/react.cljs#L78, thanks

2019-06-16 09:29 UTC, flexsurfer commented on components/src/status_im/ui/components/react.cljs
> +(def fast-image-class (get-class "fast-image"))
`get-class` retrieves class from react native package, but you need to get it from react-native-fast-image,  see how it works for image picker for example https://github.com/status-im/status-react/blob/f3aa376d167ed7d7dd5073b83f641cba7f861b03/components/src/status_im/ui/components/react.cljs#L202-L213

2019-06-17 08:03 UTC, flexsurfer commented
hey @shamardy thanks for your effort, there is an error in ios build `[!] No podspec found for react-native-fast-imag in ../node_modules/react-native-fast-image`

2019-06-26 10:42 UTC, yenda commented on react-native/src/desktop/status_im/react_native/js_dependencies.cljs
> +(def fast-image             #js {:FastImage #js {}})
Shouldn't desktop at least back up on standard image?

2019-07-01 07:44 UTC, flexsurfer commented on react-native/src/desktop/status_im/react_native/js_dependencies.cljs
> +(def fast-image             #js {:FastImage #js {}})
@vkjr ?

2019-07-01 08:00 UTC, vkjr commented on react-native/src/desktop/status_im/react_native/js_dependencies.cljs
> +(def fast-image             #js {:FastImage #js {}})
Yes, for desktop we should use default images until react-native-fast-image ported to desktop (if there is a need)

2019-07-01 08:06 UTC, flexsurfer commented on react-native/src/desktop/status_im/react_native/js_dependencies.cljs
> +(def fast-image             #js {:FastImage #js {}})
@shamardy could you take a look please, thanks

2019-07-10 13:09 UTC, flexsurfer commented
hey @shamardy any updates?

2019-07-16 11:57 UTC, flexsurfer commented
@shamardy could you rebase onto develop please, thanks

2019-08-05 09:28 UTC, oskarth commented
Closing PR as no longer active. Please re-open if this is in error.

2019-08-05 09:28 UTC, closed without merging