Add processing indicator when creating multiaccount
status-im/status-legacy pull request #8815
Opened 2019-08-22 11:44 UTC by siphiuel

Fixes #8743

2019-08-22 11:55 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 8eef2716 | [#1](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-8815/1/) | 2019-08-22 11:55:11 | ~10 min | `ios` | [:package: ipa](https://i.diawi.com/hVDfob) |

2019-08-22 12:07 UTC, yenda approved these changes

2019-08-23 05:21 UTC, flexsurfer requested changes
could you please add processing check into `:intro-wizard/step-forward-pressed` event as well, because it's still possible to press the button twice

2019-08-26 09:29 UTC, siphiuel commented
@flexsurfer Thanks, good point, fixed.

2019-08-26 09:42 UTC, flexsurfer approved these changes

2019-08-26 14:43 UTC, churik commented
Failed e2e are not related to PR.
Tested on Android 8 And IOS 11.4.1 on both recovery sign up flows. 
Work good!

2019-08-26 15:55 UTC, merged