upgrade status-go
status-im/status-legacy pull request #8850
Opened 2019-08-28 09:03 UTC by cammellos

Upgrade status-go with changes to log datasync.

status: ready

2019-08-28 09:04 UTC, flexsurfer approved these changes

2019-08-28 09:11 UTC, status-im-auto commented
### Jenkins Builds
<details>
<summary>Click to see older builds (4)</summary>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 275d64ee | [#1](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-8850/1/) | 2019-08-28 09:11:50 | ~8 min | `ios` | [:page_facing_up: log](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-8850/1/consoleText) |
| :heavy_check_mark: | 275d64ee | [#1](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-8850/1/) | 2019-08-28 09:26:25 | ~23 min | `android` | [:package: apk](https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190828-090319-275d64-pr.apk) |
| :heavy_check_mark: | 275d64ee | [#1](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-8850/1/) | 2019-08-28 09:28:04 | ~24 min | `android-e2e` | [:package: apk](https://status-im.ams3.digitaloceanspaces.com/StatusIm-190828-090318-275d64-e2e.apk) |
| :heavy_check_mark: | 275d64ee | [#2](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-8850/2/) | 2019-08-28 09:48:33 | ~11 min | `ios` | [:package: ipa](https://i.diawi.com/AFQEbn) |
</details>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | a004ee5c | [#3](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-8850/3/) | 2019-08-28 19:18:25 | ~13 min | `ios` | [:package: ipa](https://i.diawi.com/CX8s3p) |
| :heavy_check_mark: | a004ee5c | [#2](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-8850/2/) | 2019-08-28 19:24:45 | ~19 min | `android-e2e` | [:package: apk](https://status-im.ams3.digitaloceanspaces.com/StatusIm-190828-190500-a004ee-e2e.apk) |
| :heavy_check_mark: | a004ee5c | [#2](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-8850/2/) | 2019-08-28 19:25:50 | ~20 min | `android` | [:package: apk](https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190828-190502-a004ee-pr.apk) |
| | | | | | | |
| :heavy_check_mark: | 58204f93 | [#7](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-8850/7/) | 2019-08-29 06:54:53 | ~13 min | `ios` | [:package: ipa](https://i.diawi.com/v78fCK) |
| :heavy_check_mark: | 58204f93 | [#6](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-8850/6/) | 2019-08-29 07:02:18 | ~20 min | `android` | [:package: apk](https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190829-064123-58204f-pr.apk) |
| :heavy_check_mark: | 58204f93 | [#6](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-8850/6/) | 2019-08-29 07:02:41 | ~21 min | `android-e2e` | [:package: apk](https://status-im.ams3.digitaloceanspaces.com/StatusIm-190829-064122-58204f-e2e.apk) |

2019-08-28 09:26 UTC, yenda approved these changes
if the account pr is merged first please don't change status-go version because it will be a more recent one

2019-08-28 11:03 UTC, Serhy commented
@cammellos should it be tested with DataSync enabled? 
Am I right that testing scope here is that nothing should be changed with messaging in chats so a regression test required here?

2019-08-28 11:11 UTC, cammellos commented
yes, tested with datasync enabled and light regression tests in messaging, thanks!

2019-08-28 16:59 UTC, Serhy commented
Tested with DataSync enabled 1-1, Group and public chats. No regression found in this PR. 
The conflicting status-go-version.json as I understand exactly what has been warned in https://github.com/status-im/status-react/pull/8850#pullrequestreview-280700643. If that's the case, @cammellos could you please resolve it and merge?

2019-08-29 06:08 UTC, yenda requested changes
just putting a request for change hoping nobody merges that PR before the status-go PR is merged in develop

2019-08-29 06:08 UTC, yenda commented on status-go-version.json
> +    "version": "8dd932f75792db66348e4314a9bd107edf6761a0",
develop

2019-08-29 06:41 UTC, cammellos commented
@yenda could you review again, all the changes have now been added to develop?

2019-08-29 06:42 UTC, yenda approved these changes

2019-08-29 06:42 UTC, merged