Increase number on 'unread' messages indicator to +99
status-im/status-legacy pull request #9340
Opened 2019-10-30 02:40 UTC by mruzekw

Completes #8676 

### Summary

Previously the unread message counter showed 9+ if the number of unread messages was greater than 9. This PR ups that limit to 99 and will show '99+' when above that limit.

### Review notes

Translations are incomplete. It only containers a '99+' string for `en` or English.

Some file changes happened on their own during the build process. I need some guidance on how whether or not to commit these.

There also seems to be some inconsistent formatting in `en.json`, my editor normalized it automatically. Let me know if you'd like me to remove these changes.

Also, please let me know if you'd like anything organized differently.

### Testing notes

No unit tests currently.

#### Platforms

- Android
- iOS
- macOS
- Linux
- Windows

#### Areas that maybe impacted

Tab bar.
Chat list view.

##### Functional

- 1-1 chats
- public chats
- group chats

##### Non-functional

None.

### Steps to test

1-on-1 chat: Message between 2 accounts with 100 unread messages.
Group chat: Join a popular group chat and wait until 100 unread messages.

Confirm '99+' displays in both chat list item and tab bar.

Status: WIP, looking for guidance with above items in "Review notes".

2019-10-30 02:48 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | e83b32a0 | [#1](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-9340/1/) | 2019-10-30 02:48:50 | ~8 min | `ios` | [:page_facing_up:`log`](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-9340/1/consoleText) |

2019-10-30 07:07 UTC, rasom requested changes
Please make sure that all unrelated changes are excluded from pull request.

2019-10-30 07:07 UTC, rasom commented on env/dev/env/config.cljs
> + :ios "ws://localhost:3449/figwheel-ws",
Changes to this file are unnecessary, revert them please

2019-10-30 07:07 UTC, rasom commented on ios/Podfile.lock
> +  - React (0.60.6):
Same here, changes are unnecessary

2019-10-30 07:07 UTC, rasom commented on translations/en.json
> +	"counter-99-plus": "99+",
that's the only change required by PR, please revert all changes below in this file

2019-10-30 07:07 UTC, rasom commented on src/status_im/ui/components/badge.cljs
> +    (let [more-than-99 (> value 99)]
There's no real need in this `let` form as `more-than-99` is used only once and thus the condition can be inlined in `if`.

2019-10-30 07:34 UTC, errorists commented
Looks good, thanks @mruzekw and congrats on your first pr 🎉

2019-10-30 14:55 UTC, yenda commented on src/status_im/ui/components/badge.cljs
> +        (if more-than-99 (i18n/label :t/counter-99-plus) value)
```suggestion
        (if (> value 99) 
          (i18n/label :t/counter-99-plus) 
          value)
```

2019-11-01 12:09 UTC, yenda commented
@mruzekw thank  you for your first PR, could you remove the unnecessary changes?

2019-11-01 21:09 UTC, mruzekw commented
Hi @yenda, the unnecessary changes should be removed now.

2019-11-01 21:12 UTC, mruzekw commented
Should I add an accessibility label for the unread-message-counter?

2019-11-01 23:13 UTC, hesterbruikman commented
@churik wdyt?

> Should I add an accessibility label for the unread-message-counter?

2019-11-02 07:19 UTC, rasom approved these changes

2019-11-03 09:18 UTC, churik commented
@mruzekw thank you for contribution!
> Should I add an accessibility label for the unread-message-counter?
Not sure it makes sense when there can be several  unread-message-counter on the page.
Anyway please take a look into Jenkins build logs - no builds fro tests: 
[android.log](https://github.com/status-im/status-react/files/3801384/android.log)

2019-11-04 07:30 UTC, flexsurfer commented
@mruzekw please use `lein cljfmt check` and fix code formatting

2019-11-04 23:04 UTC, mruzekw commented
Thanks, @flexsurfer. Formatting should be fixed now.

2019-11-06 08:53 UTC, errorists approved these changes

2019-11-06 09:15 UTC, churik commented
Tested on IOS 13 (IPhone7) and Android8 (LG V20)

2019-11-06 10:04 UTC, merged