Hide "[#9592]Searching Message History Coming Soon" On Chat Search And "Blocked Users" When Empt
status-im/status-legacy pull request #9736
Opened 2019-12-29 21:33 UTC by tbenr

fixes #9592

status: ready

2019-12-29 21:33 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | bfa0fdf2 | [#1](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-9736/1/) | 2019-12-29 21:33:57 | ~35 sec | `android-e2e` | [:page_facing_up:`log`](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-9736/1/consoleText) |

2020-01-06 09:50 UTC, vkjr approved these changes

2020-01-06 10:26 UTC, yenda requested changes

2020-01-06 10:26 UTC, yenda commented on src/status_im/ui/screens/contacts_list/views.cljs
> +      (when (> blocked-contacts-count 0)
replace with `pos?`

2020-01-06 10:27 UTC, yenda commented on src/status_im/ui/screens/contacts_list/views.cljs
> +      (when (> blocked-contacts-count 0)
```suggestion
      (when (pos? 0)
```

2020-01-06 14:54 UTC, tbenr commented on src/status_im/ui/screens/contacts_list/views.cljs
> +      (when (> blocked-contacts-count 0)
@yenda done

2020-01-06 14:59 UTC, yenda approved these changes

2020-01-07 13:07 UTC, churik commented
Tested on IOS 13 (search and blocked users) and on Android 10 (only blocked users, search currently is not working on Android).
Looks good to me, thank you for contribution @tbenr !

2020-01-08 12:04 UTC, merged