fixes ENS to new registry
status-im/status-legacy pull request #9952
Opened 2020-01-30 20:04 UTC by decanus

uses new ENS registry. see: https://github.com/ensdomains/ens/security/advisories/GHSA-8f9f-pc5v-9r5h

2020-01-30 20:19 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | cdfb5c4d | [#1](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-9952/1/) | 2020-01-30 20:19:04 | ~14 min | `ios` | [:package:`ipa`](https://i.diawi.com/Efhh1B) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FEfhh1B)|

2020-02-03 17:55 UTC, corpetty commented
any particular thing this is waiting on?

2020-02-03 18:02 UTC, decanus commented
@corpetty code review and merge button press.

2020-02-03 18:04 UTC, corpetty approved these changes
lgtm, unless there is another place in the code referencing ENS that was missed.

2020-02-03 18:19 UTC, decanus commented
I couldn't find anything else.

2020-02-03 18:27 UTC, yenda approved these changes

2020-02-03 18:29 UTC, yenda commented
@Serhy please make a quick test of ENS relates features

@decanus lgtm, ideally we should move the contract address out of the translations but it can be done later

2020-02-04 14:05 UTC, 3esmit requested changes
testnet address dont changes?

2020-02-04 14:05 UTC, 3esmit commented on src/status_im/ethereum/ens.cljs
>     :testnet "0x112234455c3a32fd11230c42e7bccd4a84e02010"
ropsten address dont changes?

2020-02-05 10:02 UTC, decanus commented on src/status_im/ethereum/ens.cljs
>     :testnet "0x112234455c3a32fd11230c42e7bccd4a84e02010"
is testnet ropsten?

2020-02-05 10:06 UTC, 3esmit approved these changes

2020-02-06 17:14 UTC, Serhy commented
With https://i.diawi.com/UEFCFn (tested on iOS 13.3) and https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-200206-160307-7c5dec-pr-universal.apk (on Android 8.1)
- Can attach a name from another domain
- Can buy and use stateofus.eth ENS and find by this new ENS the user
- Can see ENSs (both assigned with another domain and stateofus one) in public chats and 1-1 chat.

2020-02-07 08:42 UTC, flexsurfer commented
@Serhy changed address for ens verification as well

2020-02-07 08:52 UTC, cammellos approved these changes

2020-02-07 09:40 UTC, Serhy commented
Tested https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-200207-084019-3acc45-pr.ipa on iOS 13.3 and https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-200207-084018-3acc45-pr-universal.apk on Android
- Can attach a name from another domain as well as stateofus.eth
- Can buy and use stateofus.eth ENS and find by this new ENS the user
- Can see ENSs (both assigned with another domain and stateofus one) in public chats and 1-1 chat

2020-02-07 09:42 UTC, merged